# .travis.yml

language: python
cache:
  directories:
  - "$HOME/.cache/pip"
python: 3.7
sudo: true
dist: xenial

install: "pip install -r maintenance/requirements.txt"
script: "python maintenance/github-crawler.py"
deploy:
  provider: script
  script: sh $TRAVIS_BUILD_DIR/.travis/push.sh
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
