# appveyor.yml
# See https://pythonhosted.org/CodeChat/appveyor.yml.html
# Building, testing and deployment for Windows

# Syntax for this file:
# https://www.appveyor.com/docs/appveyor-yml
# see also https://www.appveyor.com/docs/windows-images-software/#python

image: Visual Studio 2019

build: false

environment:
  matrix:
    # double backslashes required
    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: 3.9
      PYTHON_ARCH: 32

matrix:
  fast_finish: false

# double backslashes not required in set command
# python -c "import os; import pprint; pprint.pprint(os.getenv('PATH').split(';'));"

init: |
  echo PYTHON=%PYTHON% PYTHON_VERSION=%PYTHON_VERSION% PYTHON_ARCH=%PYTHON_ARCH%
  set "PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%"
  python -V

install: |
  set "PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%"
  python -V
  python -m pip install --upgrade pip
  python -m pip install -r maintenance/requirements.txt

test_script: |
  set "PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%"
  python -V
  python maintenance/github-crawler.py 1
