# https://canovasjm.netlify.app/2020/11/29/github-actions-run-a-python-script-on-schedule-and-commit-changes/

name: update-index

on:
  workflow_dispatch:
  schedule:
    # run at 15:00 UTC every day (8am PDT/UTC-7)
    - cron: '0 15 * * *'

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:

      - name: run actions/checkout@v2
        uses: actions/checkout@v2

      - name: run actions/cache@v2 - pip
        uses: actions/cache@v2
        id: pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: run actions/cache@v2 - cache
        uses: actions/cache@v2
        id: cache
        with:
          path: cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/cache.pickle') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: run actions/setup-python@v2
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: run pip install -r maintenance/requirements.txt
        if: steps.pip.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r maintenance/requirements.txt

      - name: run python maintenance/github-crawler.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python maintenance/github-crawler.py

      - name: run git commit -am "update index [ci skip]"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -am "update index [ci skip]"

      - name: run ad-m/github-push-action@v0.6.0
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
